//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdLayers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GdLayers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AnimatedDecorations {
            get {
                object obj = ResourceManager.GetObject("AnimatedDecorations", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animated Decorations are non-solid objects, that have any kind of animations that cannot kill the player and being used as decorations.
        /// </summary>
        public static string AnimatedDecorations_Description {
            get {
                return ResourceManager.GetString("AnimatedDecorations_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AnimatedHazards {
            get {
                object obj = ResourceManager.GetObject("AnimatedHazards", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animated Hazards are hazard objects that have some sort of animation and can kill the player.
        /// </summary>
        public static string AnimatedHazards_Description {
            get {
                return ResourceManager.GetString("AnimatedHazards_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AnimatedPixelDecorations {
            get {
                object obj = ResourceManager.GetObject("AnimatedPixelDecorations", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animated Pixel Decorations are non-solid objects, which are basically the same as &quot;Pixel Decorations&quot; but have some sort of animation as well.
        /// </summary>
        public static string AnimatedPixelDecorations_Description {
            get {
                return ResourceManager.GetString("AnimatedPixelDecorations_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Collectibles {
            get {
                object obj = ResourceManager.GetObject("Collectibles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collectibles are interactive objects that can be picked up by the player and be used for condition checking farther in the level.
        /// </summary>
        public static string Collectibles_Description {
            get {
                return ResourceManager.GetString("Collectibles_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FillerDecorations {
            get {
                object obj = ResourceManager.GetObject("FillerDecorations", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filler Decorations are non-solid objects that are primarely used in &quot;filling&quot; the empty spaces and add more details.
        /// </summary>
        public static string FillerDecorations_Description {
            get {
                return ResourceManager.GetString("FillerDecorations_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GamemodePortals {
            get {
                object obj = ResourceManager.GetObject("GamemodePortals", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamemode Portals are interactive objects that change the player mode once gone through, such as cube, wave, swingcopter and any other.
        /// </summary>
        public static string GamemodePortals_Description {
            get {
                return ResourceManager.GetString("GamemodePortals_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GlowDecorations {
            get {
                object obj = ResourceManager.GetObject("GlowDecorations", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glow Decorations are non-solid objects that are usually being used in pair with some other objects, they have transparency and make the other objects glow.
        /// </summary>
        public static string GlowDecorations_Description {
            get {
                return ResourceManager.GetString("GlowDecorations_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GravityPortals {
            get {
                object obj = ResourceManager.GetObject("GravityPortals", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravity portals are interactive objects that change the player gravity based on the type of portal he went through.
        /// </summary>
        public static string GravityPortals_Description {
            get {
                return ResourceManager.GetString("GravityPortals_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LaunchingPads {
            get {
                object obj = ResourceManager.GetObject("LaunchingPads", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching Pads are interactive objects that can impact the player gravity and impulse the player into the air.
        /// </summary>
        public static string LaunchingPads_Description {
            get {
                return ResourceManager.GetString("LaunchingPads_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap NonSolidBlocks {
            get {
                object obj = ResourceManager.GetObject("NonSolidBlocks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Solid Blocks are non-solid objects have no hitbox, and can be used for decorating among the solid blocks.
        /// </summary>
        public static string NonSolidBlocks_Description {
            get {
                return ResourceManager.GetString("NonSolidBlocks_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap NonSolidSpikes {
            get {
                object obj = ResourceManager.GetObject("NonSolidSpikes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Solid Spikes are &quot;fake&quot; spikes that have no hitbox and can be used in decorative purposes.
        /// </summary>
        public static string NonSolidSpikes_Description {
            get {
                return ResourceManager.GetString("NonSolidSpikes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Orbs {
            get {
                object obj = ResourceManager.GetObject("Orbs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orbs are interactive objects that repond once the player click within their hitbox, they can impact the player gravity, teleport the player, and trigger any type of objects in the game.
        /// </summary>
        public static string Orbs_Description {
            get {
                return ResourceManager.GetString("Orbs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap OtherDecorations {
            get {
                object obj = ResourceManager.GetObject("OtherDecorations", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Decorations are non-solid objects that weren&apos;t listed any above, they might represent some icons or any other decoration kind.
        /// </summary>
        public static string OtherDecorations_Description {
            get {
                return ResourceManager.GetString("OtherDecorations_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap OtherHazards {
            get {
                object obj = ResourceManager.GetObject("OtherHazards", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Hazards are hazard objects that have no specific category, neither they are animated, can kill the player.
        /// </summary>
        public static string OtherHazards_Description {
            get {
                return ResourceManager.GetString("OtherHazards_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap OtherPortals {
            get {
                object obj = ResourceManager.GetObject("OtherPortals", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Portals are interactive objects that can change the visual flow-direction, make the player dual-mode or even teleport.
        /// </summary>
        public static string OtherPortals_Description {
            get {
                return ResourceManager.GetString("OtherPortals_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap OutlineDecorations {
            get {
                object obj = ResourceManager.GetObject("OutlineDecorations", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline Decorations are non-solid objects that are basically white lines, which can be used in decorative purposes.
        /// </summary>
        public static string OutlineDecorations_Description {
            get {
                return ResourceManager.GetString("OutlineDecorations_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PixelDecorations {
            get {
                object obj = ResourceManager.GetObject("PixelDecorations", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel Decorations are non-solid objects that have lite-weighted pixel texture, usually absent of deep details.
        /// </summary>
        public static string PixelDecorations_Description {
            get {
                return ResourceManager.GetString("PixelDecorations_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Saws {
            get {
                object obj = ResourceManager.GetObject("Saws", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saws are hazard objects that usually have animation, but sometimes they dont, they will kill the player if he touches the hitbox.
        /// </summary>
        public static string Saws_Description {
            get {
                return ResourceManager.GetString("Saws_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SizePortals {
            get {
                object obj = ResourceManager.GetObject("SizePortals", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Portals are interactive objects that change the player size, that is either small or big.
        /// </summary>
        public static string SizePortals_Description {
            get {
                return ResourceManager.GetString("SizePortals_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SolidBlocks {
            get {
                object obj = ResourceManager.GetObject("SolidBlocks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid Blocks are objects that are mainly used for gameplay structuring. They always have a solid hitbox that player can interact with.
        /// </summary>
        public static string SolidBlocks_Description {
            get {
                return ResourceManager.GetString("SolidBlocks_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SolidSpikes {
            get {
                object obj = ResourceManager.GetObject("SolidSpikes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid Spikes are hazard object that will kill the player once collided .
        /// </summary>
        public static string SolidSpikes_Description {
            get {
                return ResourceManager.GetString("SolidSpikes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SortedTypes {
            get {
                object obj = ResourceManager.GetObject("SortedTypes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SpecialBlocks {
            get {
                object obj = ResourceManager.GetObject("SpecialBlocks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Blocks are interactive blocks that can affect the existing blocks, such as D-Block that allows the wave to slide on solid objects without being killed, or platformer checkpoints and other.
        /// </summary>
        public static string SpecialBlocks_Description {
            get {
                return ResourceManager.GetString("SpecialBlocks_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SpeedModifiers {
            get {
                object obj = ResourceManager.GetObject("SpeedModifiers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Modifiers are interactive objects that change the player horizontal motion speed once collides with the hitbox.
        /// </summary>
        public static string SpeedModifiers_Description {
            get {
                return ResourceManager.GetString("SpeedModifiers_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Triggers {
            get {
                object obj = ResourceManager.GetObject("Triggers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggers are interactive/non-interactive objects that can be used from changing the background color to moving objects in the game, there are plenty of triggers.
        /// </summary>
        public static string Triggers_Description {
            get {
                return ResourceManager.GetString("Triggers_Description", resourceCulture);
            }
        }
    }
}
